name: note_gps
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.0 
  cloud_firestore: ^5.1.0
  geolocator: ^12.0.0
  image_picker: ^1.1.2
  location: ^7.0.0
  google_maps_flutter: ^2.7.0
  permission_handler: ^10.0.0
  firebase_storage: ^12.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
