// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9RJKJ3mx-q3eeESJUhnE_a_-Kk5VaOh0',
    appId: '1:846138915526:web:0325ad97b498c4be7db5c7',
    messagingSenderId: '846138915526',
    projectId: 'notes-18fae',
    authDomain: 'notes-18fae.firebaseapp.com',
    storageBucket: 'notes-18fae.appspot.com',
    measurementId: 'G-MHVGGLDZYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATQy_suMiq4_5jH541-j00_D9ryakX4mY',
    appId: '1:846138915526:android:c09e1ff864e31e7d7db5c7',
    messagingSenderId: '846138915526',
    projectId: 'notes-18fae',
    storageBucket: 'notes-18fae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkeoCGCbOyAWxmIwMhHnKYiaaSJssG5lI',
    appId: '1:846138915526:ios:f790f770592051c47db5c7',
    messagingSenderId: '846138915526',
    projectId: 'notes-18fae',
    storageBucket: 'notes-18fae.appspot.com',
    iosBundleId: 'com.example.noteGps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkeoCGCbOyAWxmIwMhHnKYiaaSJssG5lI',
    appId: '1:846138915526:ios:f790f770592051c47db5c7',
    messagingSenderId: '846138915526',
    projectId: 'notes-18fae',
    storageBucket: 'notes-18fae.appspot.com',
    iosBundleId: 'com.example.noteGps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9RJKJ3mx-q3eeESJUhnE_a_-Kk5VaOh0',
    appId: '1:846138915526:web:c05bd3350db627127db5c7',
    messagingSenderId: '846138915526',
    projectId: 'notes-18fae',
    authDomain: 'notes-18fae.firebaseapp.com',
    storageBucket: 'notes-18fae.appspot.com',
    measurementId: 'G-FRMM1S0YMB',
  );
}
